apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: my-app-sb
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret

