apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: my-app-sb
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - Large