apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicaset
  labels:
    app: my-replicaset-sb
spec:
  replicas: 3
  selector: 
    matchLabels:
      type: frontend
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-app-sb
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
