apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: my-ubuntu-sb
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep","3600"]
      securityContext: 
        runAsUser: 1000
